const appointmentList = [
    {
        id: 1,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-18",
        hour: "18:00",
        timestamp: "18 Mar 2024 - 18:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 2,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-18",
        hour: "19:00",
        timestamp: "18 Mar 2024 - 19:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 3,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-18",
        hour: "20:00",
        timestamp: "18 Mar 2024 - 20:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 4,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-19",
        hour: "18:00",
        timestamp: "18 Mar 2024 - 18:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 5,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-20",
        hour: "18:00",
        timestamp: "18 Mar 2024 - 18:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 6,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-19",
        hour: "19:00",
        timestamp: "19 Mar 2024 - 19:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 7,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-20",
        hour: "19:00",
        timestamp: "20 Mar 2024 - 19:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
    {
        id: 8,
        patient: "Lucas Garieri",
        patientid: 1,
        phone: "(61) 98265-3119",
        photo: "/images/user.jpeg",
        professional: "Lucas Garieri",
        professionalid: 1,
        date: "2024-03-21",
        hour: "18:00",
        timestamp: "21 Mar 2024 - 18:00",
        status: "Confirmado",
        type: "Presencial",
        address: "Rua Boturoca 220"
    },
];

export default appointmentList;
